import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { Welcome } from '../components/Welcome'
import RecursiveTree from '../components/recursive-tree'
import { mockGroupsTreeList } from '../components/data'
import { TreeBranch } from '../components/types'

const onSelect = (value: TreeBranch) => {
  // You can put whatever here
  alert("you clicked: " + value.label)
}

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>A Group Manager in next.js</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          A group manager written in next.js
        </h1>
        <Welcome firstName={'Whoever'} lastName={'you are'}></Welcome>

        <RecursiveTree listMeta={mockGroupsTreeList} onSelectCallback={onSelect}/>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="thecloudofpauljames.net"
          target="_blank"
          rel="noopener noreferrer"
        >
        thecloudofpauljames.net
        </a>
      </footer>
    </div>
  )
}

export default Home
